import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';

const app = await readFile(new URL('../src/App.vue', import.meta.url), 'utf8');
const visualScene = await readFile(new URL('../src/components/NurseStationVisualScene.vue', import.meta.url), 'utf8');
const stationPanel = await readFile(new URL('../src/components/NurseStationPanel.vue', import.meta.url), 'utf8');
const bottomNav = await readFile(new URL('../src/components/dashboard/DashboardBottomNav.vue', import.meta.url), 'utf8');
const dashboardFrame = await readFile(new URL('../src/components/dashboard/DashboardFrame.vue', import.meta.url), 'utf8');
const areaScene = await readFile(new URL('../src/core/area-scene.ts', import.meta.url), 'utf8');
const sceneConfig = await readFile(new URL('../src/config/nurse-station-scene.ts', import.meta.url), 'utf8');

assert.match(app, /NurseStationVisualScene/);
assert.match(app, /NurseStationVisualScene[\s\S]*?v-show="isNurseStation"/);
assert.match(app, /<AreaScene3D[\s\S]*?v-show="isWard"/);
assert.match(app, /WardScene3D/);
assert.match(app, /WardPlanView/);
assert.doesNotMatch(visualScene, /nurse-station-visual__markers/);
assert.match(stationPanel, /:key="`\$\{room\.sickroomCode\}-\$\{room\.roomIndex\}`"/);
assert.match(visualScene, /&__model-state\s*\{[\s\S]*?inset:\s*0;/);
assert.doesNotMatch(visualScene, /nurse-station-visual__corridor/);
assert.match(bottomNav, /\.dash-bottom\s*\{[\s\S]*?z-index:\s*24/);
assert.match(bottomNav, /compact\?: boolean;/);
assert.match(bottomNav, /dash-bottom--compact/);
assert.match(dashboardFrame, /minimal\?: boolean;/);
assert.match(dashboardFrame, /dash-frame--minimal/);
assert.match(app, /\n\s{6}<\/div>\s+<DashboardBottomNav/);
assert.match(sceneConfig, /1-1\.glb\?v=20260831-nurse-station-1-1/);
assert.match(sceneConfig, /maxSize: \{ x: 11\.04, y: 2\.3895, z: 5\.102 \}/);
assert.doesNotMatch(areaScene, /NURSE_STATION_MODEL_HEIGHT_SCALE/);
assert.doesNotMatch(areaScene, /model\.scale\.y\s*\*=/);
assert.match(sceneConfig, /deskFov: \d+(?:\.\d+)?/);
assert.match(sceneConfig, /target: \{ x: -?\d+(?:\.\d+)?, y: -?\d+(?:\.\d+)?, z: -?\d+(?:\.\d+)? \}/);
assert.match(sceneConfig, /initialDistance: \d+(?:\.\d+)?/);
assert.match(sceneConfig, /pan: \{ xLimit: 0\.42, yMin: 0\.42, yMax: 1\.35 \}/);
assert.match(sceneConfig, /initialAngle: \{ azimuthDeg: -?\d+(?:\.\d+)?, elevationDeg: -?\d+(?:\.\d+)? \}/);
assert.match(areaScene, /const STATION_CAM_DIR = new THREE\.Vector3\([\s\S]*?Math\.sin\(STATION_INITIAL_AZIMUTH\)/);
assert.match(areaScene, /private attachNurseStationTextureOverlay\(/);
assert.match(areaScene, /new THREE\.PlaneGeometry\(overlayWidth, overlayHeight\)/);
assert.match(areaScene, /overlay\.name = `nurse-station-screen-overlay-\$\{kind\}`/);
assert.match(areaScene, /depthWrite: false/);
assert.doesNotMatch(areaScene, /this\.replaceMeshMaterialWithTexture\(object, texture\)/);
assert.match(sceneConfig, /background: 0xcfdad4/);
assert.doesNotMatch(areaScene, /nurseStationHospitalEnvironment/);
assert.doesNotMatch(areaScene, /buildNurseStationHospitalEnvironment/);
assert.doesNotMatch(areaScene, /nurse-station-hospital-environment/);
assert.match(areaScene, /this\.attachNurseStationBoardDisplays\(model\);/);
assert.match(areaScene, /(?:private )?attachNurseStationIntegrationDisplays\(parent: THREE\.Group\)/);
assert.match(areaScene, /frame\.name = `nurse-station-integration-frame-\$\{kind\}`/);
assert.match(areaScene, /const z = -1\.365;/);
assert.match(areaScene, /createIntegrationDisplay\(-1\.1, 'whiteboard', 0\.82\)/);
assert.match(areaScene, /createIntegrationDisplay\(1\.1, 'roomStatus', 0\.82\)/);
assert.doesNotMatch(areaScene, /createIntegrationDisplay\(0,/);
assert.match(areaScene, /ctx\.font = 'bold 58px "Microsoft YaHei", sans-serif';/);
assert.match(areaScene, /ctx\.font = 'bold 50px "Microsoft YaHei", sans-serif';/);
assert.match(areaScene, /this\.scene\.background = new THREE\.Color\(showCorridor \? SCENE_BG : NURSE_STATION_BG\);/);
assert.match(areaScene, /\['dashboard', \['Screen_Main', 'Screen_Main_Frame'\]\]/);
assert.match(areaScene, /\['taskQueue', \['Screen_Work_01', 'Monitor_UI_01_00'\]\]/);
assert.match(areaScene, /\['wardStatus', \['Screen_Work_02', 'Monitor_UI_02_02'\]\]/);
assert.match(areaScene, /\['bedMonitor', \['Screen_Work_03', 'Monitor_Frame_03'\]\]/);
assert.match(areaScene, /\['deviceHealth', \['Screen_Work_04', 'Monitor_Frame_04'\]\]/);
assert.match(areaScene, /'任务队列'/);
assert.match(areaScene, /'病房状态'/);
assert.match(areaScene, /'床位监测'/);
assert.match(areaScene, /'设备与环境'/);
assert.match(areaScene, /\['clock', \['Clock_Display', 'Clock_Frame'\]\]/);

console.log('Nurse-station scene boundary tests passed.');
