async (page) => {
 const result = {};
 const origin = 'http://127.0.0.1:5174/';
 const sceneModule = '**/src/core/hospital-exterior/hospital-intro-scene.ts*';
 await page.route('**/swp/**', route => route.fulfill({status:200,contentType:'application/json',body:JSON.stringify({code:0,data:[],msg:'isolated browser test'})}));
 await page.route('**/db-adapter/**', route => route.fulfill({status:200,contentType:'application/json',body:'[]'}));
 await page.route('**/models/**', route => route.abort());
 await page.setViewportSize({width:1440,height:900});
 await page.emulateMedia({reducedMotion:'no-preference'});
 await page.goto(origin);
 await page.evaluate(() => { for (const key of ['TokenKey','DIGITAL_TWIN_AUTH_USER','DIGITAL_TWIN_AUTH_ROLE']) sessionStorage.removeItem(key); });
 await page.reload();
 await page.locator('.hospital-opening canvas').waitFor({timeout:15000});
 if (await page.locator('.swp-login').count()) throw Error('Login appeared before introduction completed');
 await page.getByRole('button',{name:'暂停动画',exact:true}).click();
 await page.getByRole('button',{name:'继续播放',exact:true}).waitFor();
 await page.waitForTimeout(600);
 await page.screenshot({path:'output/playwright/login-intro-production-desktop.png'});
 await page.getByRole('button',{name:'跳过动画'}).click();
 await page.locator('.swp-login input[name=username]').waitFor();
 await page.waitForFunction(() => document.activeElement?.getAttribute('name') === 'username', {}, {timeout:3000});
 if (await page.locator('.hospital-opening canvas').count()) throw Error('Canvas survived skip');
 result.skip = true;
 await page.reload();
 await page.locator('.hospital-opening canvas').waitFor();
 await page.locator('.swp-login input[name=username]').waitFor({timeout:15000});
 result.automaticFinish = true;
 await page.setViewportSize({width:390,height:844});
 await page.reload();
 await page.locator('.hospital-opening canvas').waitFor();
 await page.getByRole('button',{name:'暂停动画',exact:true}).click();
 await page.getByRole('button',{name:'继续播放',exact:true}).waitFor();
 await page.waitForTimeout(600);
 await page.screenshot({path:'output/playwright/login-intro-production-mobile.png'});
 const mobile = await page.getByRole('button',{name:'跳过动画'}).boundingBox();
 if (!mobile || mobile.x < 0 || mobile.x + mobile.width > 390 || mobile.y + mobile.height > 844) throw Error('Mobile skip outside viewport');
 await page.setViewportSize({width:844,height:390});
 await page.waitForTimeout(300);
 await page.screenshot({path:'output/playwright/login-intro-production-landscape.png'});
 const landscape = await page.getByRole('button',{name:'跳过动画'}).boundingBox();
 if (!landscape || landscape.y + landscape.height > 390) throw Error('Landscape skip outside viewport');
 await page.getByRole('button',{name:'跳过动画'}).focus();
 await page.keyboard.press('Enter');
 await page.locator('.swp-login input[name=username]').waitFor();
 result.mobileAndKeyboard = true;
 await page.emulateMedia({reducedMotion:'reduce'});
 await page.reload();
 await page.locator('.swp-login input[name=username]').waitFor();
 if (await page.locator('.hospital-opening').count()) throw Error('Reduced motion did not bypass intro');
 result.reducedMotion = true;
 await page.emulateMedia({reducedMotion:'no-preference'});
 await page.route(sceneModule, route => route.abort());
 await page.reload();
 await page.locator('.swp-login input[name=username]').waitFor();
 await page.getByText('医院外景暂不可用，您可正常登录。',{exact:true}).waitFor();
 result.moduleFailure = true;
 await page.unroute(sceneModule);
 let releaseImport;
 await page.route(sceneModule, async route => { await new Promise(resolve => { releaseImport = resolve; }); await route.continue(); });
 await page.reload({waitUntil:'domcontentloaded'});
 await page.getByRole('button',{name:'跳过动画'}).click();
 await page.locator('.swp-login input[name=username]').waitFor();
 releaseImport?.();
 await page.waitForTimeout(500);
 if (await page.locator('.hospital-opening canvas').count()) throw Error('Late import resurrected scene');
 await page.unroute(sceneModule);
 result.lateImportAfterSkip = true;
 await page.addInitScript(() => {
  if (sessionStorage.getItem('intro-test-no-webgl') !== '1') return;
  const original = HTMLCanvasElement.prototype.getContext;
  HTMLCanvasElement.prototype.getContext = function(type,...args) { return type === 'webgl' || type === 'webgl2' ? null : original.call(this,type,...args); };
 });
 await page.evaluate(() => sessionStorage.setItem('intro-test-no-webgl','1'));
 await page.reload();
 await page.locator('.swp-login input[name=username]').waitFor();
 await page.getByText('医院外景暂不可用，您可正常登录。',{exact:true}).waitFor();
 await page.evaluate(() => sessionStorage.removeItem('intro-test-no-webgl'));
 result.webglFailure = true;
 await page.setViewportSize({width:1440,height:900});
 await page.evaluate(() => {
  const role={id:'intro-test-role',roleName:'测试角色'};
  sessionStorage.setItem('TokenKey','synthetic-intro-test-session');
  sessionStorage.setItem('DIGITAL_TWIN_AUTH_USER',JSON.stringify({id:'intro-test-user',userName:'intro-test-user',roleList:[role]}));
  sessionStorage.setItem('DIGITAL_TWIN_AUTH_ROLE',JSON.stringify(role));
 });
 await page.reload();
 await page.locator('.app-session').waitFor();
 await page.waitForTimeout(500);
 if (await page.locator('.hospital-opening').count()) throw Error('Authenticated page replayed introduction');
 result.authenticatedBypass = true;
 await page.evaluate(() => {
  const instance=document.querySelector('.app-session').__vueParentComponent;
  instance.setupState.handleLogout();
 });
 await page.locator('.swp-login input[name=username]').waitFor();
 if (await page.locator('.hospital-opening').count()) throw Error('Logout replayed introduction');
 if (await page.evaluate(() => sessionStorage.getItem('TokenKey') !== null)) throw Error('Logout failed to clear session');
 result.logoutWithoutReplay = true;
 return result;
}
